---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Monitors:
    - Portainer:
        href: https://10.1.1.120:9443/
        description: Docker Management

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
